### ISSUE TITLE
maxFileSize for videos - unable to upload higher than 40MB

### ISSUE THREAD

**Issue by marclundgren** [cloudinary/cloudinary_js#137]
Hi there,

When I configure the `cloudinary-direct-file` to have a high limit (e.g. 500MB), the `POST` request fails as such:

```
net::ERR_CONNECTION_RESET
```

```
POST https://api.cloudinary.com/v1_1/ralliohq/auto/upload
Referrer Policy:no-referrer-when-downgrade
Provisional headers are shown
Accept:application/json, text/javascript, */*; q=0.01
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarypYQSgXlF0CYBRBkB
Origin:http://localhost:5000
Referer:http://localhost:5000/dashboard/franchisor/5/database/videos/new
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
X-Requested-With:XMLHttpRequest
X-Unique-Upload-Id:~~~
```

The request payload contains a public id, timestamp, signature, api_key, file - but no reference to maxFileSize. As a result, I am unable to upload any video file greater than 40MB. We're paying for the premium cloudinary service, and should be qualified for up to 1GB AFAIK. Am I missing something?

Thank you!

https://github.com/mileszim/ember-cli-cloudinary/blob/master/addon/components/cloudinary-direct-file.js#L49

**Comment by taragano** [comment]
Hi @marclundgren,

1. ERR_CONNECTION_RESET errors usually mean the issue is related to connection issues, we don't return such errors from our server.
2. Please refer to the "Usage Limits" section in your [Account settings page](https://cloudinary.com/console/settings/account) to make sure the uploaded resource fits your account's file size limit. Note that the limits are different depending on the type (image/video/raw).
3. Make sure that resources larger than 100MB need to be [uploaded in chunks](https://cloudinary.com/documentation/upload_videos#chunked_video_upload)

If this still doesn't help, please feel free to share some more information and code snippets of how you performed the upload, and the timestamp of an example faulty request. 

If privacy is an issue, please feel free to [open a ticket](https://support.cloudinary.com/hc/en-us/requests/new) and our support team will be happy to assist.

**Comment by taragano** [comment]
Adding some more information, after some consultation with our dev team:

1. The `maxFileSize` parameter is a client-side validation parameter (e.g., to display an error message before uploading the file), therefore it won't be included as part of the HTTP request itself.
2. As mentioned previously, resources larger than 100MB should be uploaded chunked, however, It seems that the `ember-cli-cloudinary` library currently doesn't have the `maxChunkSize` parameter implemented, which is necessary for such requests.

A possible workaround would be to alter the `ember-cli-cloudinary` library's code to something like the following to make it work:

```
didSetData: Ember.observer('data-form-data', function() {
    Ember.run.next(this, function() {
      this.$().cloudinary_fileupload({
        disableImageResize: this.get('disableImageResize'),
        imageMaxWidth:      this.get('imageMaxWidth'),
        imageMaxHeight:     this.get('imageMaxHeight'),
        acceptFileTypes:    this.get('acceptFileTypes'),
        maxFileSize:        this.get('maxFileSize'),
        maxChunkSize:       this.get('maxChunkSize') // <-- add this line
      });
    });
  }),
```

**Comment by marclundgren** [comment]
👍
