### ISSUE TITLE
Responsive width 'null' on high DPR devices

### ISSUE THREAD

**Issue by woodyrew** [cloudinary/cloudinary_js#217]
When using the following responsive functionality

```js
const cl = cloudinary.Cloudinary.new({ cloud_name: 'MY_CLOUD' });
cl.responsive();
```

The width is being set to `null` on DPR: 3 devices.
Let me know if you need more information.

**Comment by aleksandar-cloudinary** [comment]
Hi @woodyrew. Thanks for sharing this. Which device have you tried this on? Could you please run the following JSFiddle (https://jsfiddle.net/6kscbghp/) - https://jsfiddle.net/6kscbghp/show on that device and see if you can reproduce it?

I'm attaching a screenshot below of testing the above JSFiddle via BrowserStack on iPhone X which supports DPR 3. In the network tab, it shows the sample image being requested with the `dpr_3` transformation.

<img width="1199" alt="Screenshot 2020-03-26 at 13 33 36" src="https://user-images.githubusercontent.com/48053320/77653291-6bda3a80-6f67-11ea-887a-b5c4f666d4d8.png">

**Comment by woodyrew** [comment]
Hi @aleksandar-cloudinary ,

Thanks for the prompt response. I've amended the fiddle to reproduce the issue [https://jsfiddle.net/co8tndbq/4/](here).

Here's a screenshot of the issue
![2020-03-26_3ee8](https://user-images.githubusercontent.com/1902064/77662436-c5486680-6f73-11ea-828c-22cb0b84ce14.png)

The `dpr_` parameter hasn't been set correctly to `dpr_3.0` for some reason either but you can see the `width` attribute has been set to `null`.

**Comment by aleksandar-cloudinary** [comment]
Thanks, @woodyrew. That does indeed happen in this case as your Width is hardcoded and not 'auto' which should be the value when using the responsive JavaScript solution. In fact, it will be null in all cases and not just for devices with DPR 3. For example, locally on a Mac I get null even with DPR 2.
Regarding the DPR - Yes, I get the same behaviour trying to lower or increase the DPR when using the Chrome emulator. It takes the actual DPR of the screen. If you test on BrowserStack it'll pick up the correct one based on the device. If you want to test without BrowserStack then you can set the DPR by adding `window.devicePixelRatio = 3;` before the `cl.responsive( );` is called.

**Comment by woodyrew** [comment]
Thanks @aleksandar-cloudinary,
Some great tips and information. Is there a way to set a `data-` attribute to tell `cl.responsive();` to not set the width but still do everything else to load the image?

**Comment by aleksandar-cloudinary** [comment]
Hi @woodyrew,
In general, when using the responsive solution it's recommended that you use `w_auto` as a minimum in order for that to get replaced with the actual width of the container for the image when the `responsive()` method is called and thus return an image with appropriate width to where it's being displayed. If you are not using `w_auto` then you can still use `dpr_auto` and that will work and load the image, however, the size of it would be 2x or 3x the original due to the `dpr_` value.

I'm not certain on your exact use-case and why you'd like to use the responsive image solution without an auto width, but there is still one thing that may work for you.

As I understand, you would like to hardcode the width (`w_`) value and have `dpr_auto` but ensure that the width attribute on the image is not `null`. There is indeed a way to achieve that. For example, with your JSFiddle, you can set a fixed/hardcoded width e.g. (`w_100`) in the URL and also keep `dpr_auto`. To ensure the width attribute is not `null` when the `responsive()` method runs, you can include the `data-width` attribute to the same value as the `w_` you hardcoded in the URL. Once you have all of that, the width attribute of the image will not be null, but rather the value you set in `data-width`. As expected, the `dpr_auto` will correctly be replaced with the relevant value depending on the device.

Please see the modified JSFiddle (https://jsfiddle.net/9vufopbh/) that uses the `data-width="200"` with hardcoded matching `w_200` and `dpr_auto`. If you inspect the element after running you'll notice that the <img/> width is no longer `null`, the requested width from Cloudinary is 200 and DPR value is replaced correctly.

**Comment by woodyrew** [comment]
Perfect, thank you very much. Most of the time we use `w_auto` but have a couple of cases, e.g. profile picture where we want it to be set to a specific px size.

I closed the issue.
