### ISSUE TITLE
Bump bower to v1.0.21

### ISSUE THREAD

**Issue by twler** [cloudinary/cloudinary_js#44]
It is currently at maxed at v1.0.12

**Comment by tocker** [comment]
Hi @twler,
Thanks for using Cloudinary!

Regarding the bower version, you may be looking at the wrong package.
Our package is <tt>cloudinary_js</tt> (also named `jquery_cloudinary`). There is another copy of our package which is not maintained by us and is named `cloudinary` in bower.

In order to get the correct package, please use:
```sh
bower install cloudinary_js
```
or in your bower.json file,
```json
"dependencies": {
    "cloudinary_js": ">=1.0.21"
  },
```

Please let us know if this solution worked for you. Feel free to contact us here or at our support page (http://support.cloudinary.com/home).

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
