### ISSUE TITLE
Is whole library needed just for responsive handling?

### ISSUE THREAD

**Issue by ziggamon** [cloudinary/cloudinary_js#82]
Hi,

I just want responsive images to work to save on bandwidth for low-bandwidth users. 
Is there a way of doing that without loading the whole 50 KB library?

Thanks in advance,
Sergej

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

Regardless, note that our JS responsive support reloads the image in cases when the window is sized-up. For low-bandwidth users you may want to consider using other solutions than responsive images, like tweaking quality and size, use automatic format conversion, and more.
