### ISSUE TITLE
Option to serve downscaled large images if one is already cached

### ISSUE THREAD

**Issue by gausie** [cloudinary/cloudinary_js#84]
It would be good if, when a large version of an image has already been cached and a smaller version is requested, that the large one is supplied in a downscaled state.

**Comment by roeeba** [comment]
Can you please provide an example, which demonstrates the use-case? Note that each derived (i.e., scaled) version is represented by its own URL and is cached separately. If you are referring to an updated original image, make sure you set `invalidate` to `true` in order to refresh the cache. Please see [here](https://support.cloudinary.com/hc/en-us/articles/209048985) for more information.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by prokilogrammer** [comment]
Can I pass `invalidate` to .upload method in the Javascript SDK?

**Comment by roeeba** [comment]
Hi @prokilogrammer , unsigned uploads are restricted from deleting or overwriting resources. Therefore there is no use in invalidating. In order to update a resource you will have to use one of the server-side frameworks (Node.js, PHP, etc).

**Comment by prokilogrammer** [comment]
Oh interesting. I thought cloudinary_js code was also used in NodeJS where I use signed requests. Didn't realize there was a different package for it. Thanks!

**Comment by roeeba** [comment]
The Node.js library indeed uses cloudinary_js, but while the core library is pure client-side - on node.js you can also generate signatures and perform signed requests.
