### ISSUE TITLE
Hidden input image_id (data-cloudinary-field) gets URL not public_id

### ISSUE THREAD

**Issue by partlyhuman** [cloudinary/cloudinary_js#90]
I'm a newcomer to Cloudinary so apologies if I'm misunderstanding how this should work. But using jQuery direct image upload, I was expecting that the hidden `<input>` referenced by the `data-cloudinary-field` attribute on the uploader, should be getting the `public_id` of the uploaded image. However, it is being set to a relative URL of the uploaded image, e.g. 

    <input type="hidden" name="photo_id" value="image/upload/v1466101544/5760acba92218923ad821b98.jpg#281171ba75eb9609854470ed8befbc7894f4c799">`

It makes more sense to me that the public_id is added to that field, so that you could save that when accepting the form submission, and later query with `cloudinary.image(model.photo_id)`, or on client side with `$.cloudinary.image($('input[name=photo_id]').val())`. Neither works with this URL.

I can get the correct `public_id` by listening to the `cloudinarydone` event, but I was hoping to use the built-in functionality as described in the documentation:

> When uploading is completed, the identifier of the uploaded image is set as the value of a hidden input field of your selected name (e.g., image_id in the example above).

http://cloudinary.com/documentation/jquery_image_upload#direct_uploading_from_the_browser

Ideas? Thanks!

**Comment by taragano** [comment]
The returned identifier is a string that represents various details about the uploaded image, including its resource_type, type, version, public_id, format, and signature. In order to get the public ID exclusively, you'll need to either parse the string, or use the `public_id` as returned by the `cloudinarydone` event as you've mentioned. You can have a look at the following for an example (taken from our Rails sample project):
https://github.com/cloudinary/cloudinary_gem/blob/master/samples/photo_album/app/views/photos/new_direct.html.erb#L77-L83

**Comment by partlyhuman** [comment]
If this is the intended result, may I suggest clarifying the documentation? I read "the identifier of the uploaded image" to mean "the uploaded image's public_id." Thank you!
