### ISSUE TITLE
Provide an utility method to parse public_id and transformations from given url string

### ISSUE THREAD

**Issue by snimavat** [cloudinary/cloudinary_js#94]
Its just like reverse of wloudinary.url() - need a way to get public_id and transformations from given cloudinary url

**Comment by taragano** [comment]
Hi @snimavat,

Can you please share some more information about your use-case and requirements?

Thanks,
Itay

**Comment by snimavat** [comment]
So, We have existing images on the page, and want ability for user to resize the images (its some thing like cms).

So, when user is done using the resize, we want to grab the image url, parse public id and existing transformations from it, and change the transformations to apply the new size of the image, and put the image back to the page.

So in short,  need ability to parse the public_id/transformations from any given cloudinary image url.
Its just like doing the revese of $.url()

**Comment by jakey-wan-kenobi** [comment]
Yeah it seems like a pretty useful feature to be able to take a Cloudinary URL and then parse the public ID from it. So you can take a given URL, grab the public ID, and then perform transforms on those images before loading them to the view.

**Comment by iamthefox** [comment]
Any updates on this?

**Comment by eyalktCloudinary** [comment]
Hi @iamthefox , currently we still do not have such feature. 
I've opened a feature request for that matter. Thanks!

**Comment by taragano** [comment]
@love2dishtech Will you please share some more context of your use-case?
If you have the image's public ID, you can use our SDKs to generate URLs with any transformation of your choice. Was wondering what data do you have to begin with vs the results you're after.
Thanks

**Comment by love2dishtech** [comment]
Sure, I am using [Netlify CMS](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-media-library-cloudinary/src) for a static gatsby site. The widget I use with that provides a unique raw image url of the uploaded file.

Adding this to the static site does not offer a responsive template with customizable transformations. What I am interested is to have the existing transformations stripped out of the url and extracting the public_id. This allows me to later on apply custom transformations and offer multiple responsive images.

**Comment by ronen-burin** [comment]
@love2dishtech, thank you for your response. Following the thread above. You can parse the URL you get from Cloudinary. The PUBLIC_ID is the last component in the url: https://res.cloudinary.com/<cloud_name>/image/upload/<public_id>.<format>

See also https://cloudinary.com/documentation/image_transformations

Thanks.

**Comment by love2dishtech** [comment]
Appreciate the directions. I was already following this thread, but the challenge is that public id can have folders and subfolders which means if we have to split it something like `url.split("/")` we cannot simply pick the last one. Rather, we would have to potentially parse the entire url splits. However, there are certain optional url path fragments like transformations and versions which mean we have to know exactly how to identify those.

If I am not wrong, this would come out to be a complicated logic and something that might change in future as Cloudinary adds new feature. Please correct me if I am wrong.

**Comment by ronen-burin** [comment]
@love2dishtech, if possible, please provide an example  URL.
**Note that the SUB-FOLDERS are part of the public ID.**

so assuming you **don't** have any transformation there are 2 options:
res.cloudinary.com/<cloud_name>/image/upload/<public_id>    ;or 
res.cloudinary.com/<cloud_name>/image/upload/<version>/<public_id>

**Comment by ronen-burin** [comment]
@love2dishtech, Looking on the code of the integration,
Set the option output_filename_only to be TRUE and you'll get the URL without the transformation:
res.cloudinary.com/<cloud_name>/image/upload/<public_id>    ;or 
res.cloudinary.com/<cloud_name>/image/upload/<version>/<public_id> 
it will be easier to parse.

Reference: 
https://github.com/netlify/netlify-cms/blob/3903acb431998b5a060825f2d600b4a7cb1a010a/packages/netlify-cms-media-library-cloudinary/src/index.js#L29

**Comment by DPOLocalAaronO** [comment]
This would be extremely useful. In my project, I need to be able to parse all of the transformation information out of a url ( complicated like /image/upload/c_crop,w_1503,h_939,x_497,y_155/w_754/images/u6lxi40j5ndkshekel423kals.jpg ).

**Comment by igy** [comment]
After some discussion with the SDK team, we've decided not to add a public method to the SDK for parsing / reverse-engineering the URLs into the differents components at this time.

Our recommendation is that when storing asset details, you store the different fields which uniquely identify an image separately (e.g. type, resource_type, format, public_id) and then use the SDK to create the delivery URL, rather than the opposite  - the responses from the admin API, upload API, and our upload and media library widgets will give those fields separately for that reason.

You can, of course, build your own method to do this based on how you're using the URLs, but we recommend storing the image identifiers rather than the URLs, then building the URLs with transformation options which match where in your application you're using the assets (e.g. based on the container, design, etc)

**Comment by deslittle** [comment]
I was looking for a solution for the same thing while using the Media Editor widget. The export function only gives the transformations in string format, "e.g. `'c_crop,h_2496,w_3024,x_0,y_1536/c_scale,h_2496,w_3024'` ". I have no option at that point to apply more transformations at a later point (I am trying to apply the ocr blur effect).

Perhaps in the public API, allow users to pass in transformations as a string, e.g.
`var tag = cl.imageTag("sample.jpg").transformation("c_crop,h_2496,w_3024,x_0,y_1536/c_scale,h_2496,w_3024").chain().gravity('ocr_text').effect("e_blur_region:800").toHtml();`

**Comment by eyalktCloudinary** [comment]
@deslittle Thanks for reaching out!
It sounds like you're looking for our `rawTransformation` parameter -
https://cloudinary.com/documentation/image_transformation_reference#raw_transformation_parameter
This parameter allows you to pass the transformation as a string.

When using the JS SDK you can set the raw transformation in the following way -
```
var tag = cl.imageTag("sample.jpg").transformation().rawTransformation("c_crop,h_2496,w_3024,x_0,y_1536/c_scale,h_2496,w_3024").toHtml();
```
In order to add additional transformations, such as the blur effect and the ocr_text gravity, you can chain them. For instance -
```
var tag = cl.imageTag("sample.jpg").transformation().rawTransformation("c_crop,h_2496,w_3024,x_0,y_1536/c_scale,h_2496,w_3024").chain().gravity('ocr_text').effect("e_blur_region:800").toHtml();
```
You can use the below JS fiddle as a reference -
https://jsfiddle.net/eyalkt/ydf215oh/

**Comment by maqduni** [comment]
I guess the only way to that would be parsing a url using regular expressions. Here's a couple of methods I wrote that you could use:

```js
const extractImageIdFromUrl = (source) =>
{
    const regex = /\/upload\/v\d{8,12}\/(.+)$/;
    const matches = regex.exec(source);

    if (matches) {
        console.log(matches[1]);
    }
};
const parseTransformationFromUrl = (source) => {
    const regex = /(?<=\/image\/upload\/)([a-z]_[^\/]*)(?=\/)/;
    if (regex.test(source))
    {
        const matches = regex.exec(source);
        const params = matches[0].split(',').filter(param => !!param).reduce((prev, curr) => {
            const splitParam = curr.split('_');
            prev[splitParam[0]] = splitParam[1];

            return prev;
        }, {});

        var transformation = new Transformation();
        for (const [paramKey, paramValue] of Object.entries(params))
        {
            try
            {
                switch (paramKey)
                {
                    case "a":
                        transformation.angle(parseInt(paramValue));
                        break;
                    case "w":
                        transformation.width(parseInt(paramValue));
                        break;
                    case "h":
                        transformation.height(parseInt(paramValue));
                        break;
                    case "c":
                        transformation.crop(paramValue);
                        break;
                    case "r":
                        transformation.radius(paramValue);
                        break;
                    case "x":
                        transformation.x(paramValue);
                        break;
                    case "y":
                        transformation.y(paramValue);
                        break;
                    case "f":
                        transformation.fetchFormat(paramValue);
                        break;
                    default:
                        break;
                }
            }
            catch (ex)
            {
                console.error(ex, "Can't parse Cloudinary source Url parameters.");
            }
        }

        console.log(transformation.serialize());
        return transformation;
    }

    return null;
};
```

They don't take into account all variations of the url, especially the version number that might appear anywhere in the url after `/image`.

**Comment by matthew-dean** [comment]
@igy If the Cloudinary team isn't going to provide this utility function, can you at least provide a reference for all the types of URLs that may be generated? Like a testing suite?

@ronen-burin says the format is:
> `https://res.cloudinary.com/<cloud_name>/image/upload/<public_id>`

Yet @maqduni says:

> They don't take into account all variations of the url, especially the version number that might float anywhere in the url after /image.

**Comment by igy** [comment]
In general, we recommend that when storing an asset's details in your own database, you do so using the individual fields that are needed to create a new URL for that asset.

That is, the resource_type, type, public_id, format, and (if not implied by your configuration), the cloud name.

When working with the upload widget or media library widget, the callbacks sent by those widgets include each of those values in separate fields so you can use that to build the URL rather than trying to parse it from the url or secure_url fields. 

Using the Media Library Widget as an example, the callback contains the same JSON fields you'd receive in response to an Upload API call: https://cloudinary.com/documentation/media_library_widget#3_create_your_callback_function

It's not currently planned to add a helper method to our client SDKs to 'reverse' a derived asset URL into the component parts. In addition to this not being the recommended implementation method, there's a wide variation in possible valid formats of URLs, especially when using less-common features or options. Effectively, there isn't any simple method / regex / etc that can parse all the possible formats in a reliable way, so we recommend building the URL based on knowledge of the asset's details, and knowledge of how you'd like it transformed for delivery.

Another significant issue is that there is ambiguity between different parts of the URL and possible overlapping options: when processing a URL on our server side, we may need information about your account, account settings, and the contents of the account to certainly map an incoming URL to a particular derived image, and without that context it's not possible to certainly extract the relevant fields from the URL.

For example, at the beginning of the URL the first part could be:
res.cloudinary.com/<CLOUD NAME>, <CLOUDNAME>-res.cloudinary.com, <CLOUDNAME>-ressh.cloudinary.com/, <CUSTOMER HOSTNAME>/<CLOUD_NAME>/image.., <CUSTOMER DOMAIN NAME>/image..., <CUSTOMER DOMAIN NAME>/<CUSTOM PATH>/image and possibly some others based on customer-specific customizations or legacy integrations

Later in the URL, the resource type and type are optional if the asset is 'image' and 'resource' respectively, or can be replaced with a shortcut that's part of our "SEO-friendly URLs" features: https://cloudinary.com/documentation/advanced_url_delivery_options#seo_friendly_media_asset_urls

Then towards the end of the URL, there's possible ambiguity between folder names in the public_id path, the optional version number, and transformation options. There are also SEO features where the public_id and format won't be at the end of the URL because the end of the URL is customer-chosen text used for SEO-purposes.

Essentially, it's much easier to build a URL than to reverse-engineer it, and if at all possible we recommend updating how the asset details are stored in your database to be based on the component pieces, or having a workflow that obtains those details when you need them, instead of storing a delivery URL for the original asset and then trying to modify it later.

That said, if you have a workflow that requires attempting parsing an existing asset delivery URL manually, the most common URL format (which is the format returned by our API for an account with default configuration) can be found here: https://cloudinary.com/documentation/image_transformations#transformation_url_structure

Additionally, a former engineer from one of our frontend teams released a personal project which includes a URL parsing function which can extract the public_id from common URL formats, so you can use it in a new call to cloudinary.url() or the equivalent method in the SDK that you're using. 

I recommend checking it carefully before using it or something similar to work backwards from an existing URL, but you may find it useful in preparing a custom solution: https://cloudinary-build-url.netlify.app/
